pennmush/pennmush

BUGS
CHANGES.186
FAQ
Makefile.in
README
UPGRADING
game/README
game/txt/hlp/penncode.hlp
game/txt/hlp/penntop.hlp
options.h.dist
win32/README.txt

A few little obsolete references here and there, and replacing Google Code URLs with Github equivalent.

Docs updates

---

.gitignore
Makefile.in
test/TestHarness.pm
test/testhastype.pl
test/testpage.pl

Three tests currently fail out of the box. Now they don't. :sparkles:

Fix broken tests

---

CHANGES.186
game/txt/hlp/pennv186.hlp
src/extchat.c

PRing so that one of the other devs can take a look, since my C is still very very rusty.
Resolves #870.

Remove very ancient @channel public=on syntax

---

.gitignore
CHANGES.186
I18N
Makefile.in
game/txt/hlp/pennv186.hlp
po/hr_HR.pox
po/nl_NL.pox
po/no_NO.pox
po/pennmush.pot
src/Makefile.in
src/funmisc.c
src/version.c

I had some issues testing the localization, can't seem to get Penn to switch into a non-English language, so would appreciate another set of :eyes: on that.
Closes #994.

Add git revision info to @version and version().

---

src/Makefile.in

Reverts pennmush/pennmush#1000
Has issues.

Revert "Only try to run gperf if it's present"

---

game/txt/hlp/pennflag.hlp

Doing Mike's job for him since he is too lazy to do it :P

Add missing "open_ok" flag to flag list.

---

README

s/leave a programming/leave a program/

Fix a spelling error

---

Makefile.in

Changes in the lines 73-75 : Added condition with would remove the files only if they exist instead of bailing out an error that the files don't exist

Fix in the install section

---

hdrs/parse.h
src/bsd.c
src/cmds.c

See discussion on issue #1232 
Uses 60 second timeouts.

Improve handling of libcurl requests

---

hdrs/ansi.h
hdrs/mushtype.h
hdrs/notify.h
src/bsd.c
src/function.c
src/notify.c
src/websock.c

See title and #1235 discussion.

Remove WITHOUT_WEBSOCKETS tests. Closes #1235

---

src/sql.c

I'm still not sure if it'll actually fix the issue in #1177 but the existing code is dumb and this fixes that.
(Need to test on M\*U\*S\*H before actually merging)

Rewrite penn_mysql_free_sql_query to avoid a possible infinite loop.

---

CHANGES.187.md
src/attrib.c
test/testatree.t

Make lattrp() behave like 1.8.6 again.

---

hdrs/mushsql.h
src/connlog.c
src/db.c
src/help.c

(Introduced in sqlite-325 branch) Fixes #1250

Fix a bug passing an invalid pointer to sqlite3_exec

---

src/bsd.c
src/comp_w8.c
src/game.c
src/htab.c
src/info_slave.c
src/log.c
src/mysocket.c
src/myssl.c
src/sig.c
src/ssl_slave.c
src/wait.c
test/PennMUSH.pm

Improves logging a bit -- changes the timestamps to be less US-centric, and adds timestamps/etc. to a lot more logged messages.

Log fixups

---

configure
configure.in
src/markup.c
src/timer.c

Fixes a bunch of small Windows things and improvements for pcre2 jit stuff.

Misc windows fixes

---

src/bsd.c

This PR modifies FUNCTION(fun_oob) to allow it to send it's package to multiple players. It uses the same logic from FUNCTION(fun_pemit) and do_pemit() to parse the player list, and keeps the existing OOB logic for looking up players and determining permissions.
The error return messages were slightly modified. Instead of having separate #-1 errors for player not found and permission denied, there is one combined error for #-1 NO VALID PLAYERS. This error occurs at the end if there is both a failure (invalid player, invalid permissions), and the number of successes is 0. If there are 0 failures or more than 0 successes, then it returns the number of successes (even if that number is 0).

Allow oob() to send to multiple players.

---

aclocal.m4
configure
configure.in
hints/aix.txt

Assorted fixes and portability tweaks, mostly thanks to Oleo testing a bit on an AIX system.

Autoconf fixes

---

CHANGES.188.md
hdrs/sqlite3.h
hdrs/sqlite3ext.h

Update sqlite to 3.27.1

---

CHANGES.188.md
game/txt/hlp/penncmd.hlp
hdrs/mushtype.h
src/bsd.c

Same as before, with a proper flag bit.. and without the whitespace changes.
Closes #1275

Noquota PR 

---

CHANGES.188.md
hdrs/sqlite3.h
src/db.c

Mostly bug fixes in this release.

Update to Sqlite 3.29.0

---

Makefile.in

This appears to have been missed in 2fcd573.

Update PCRE2_DIR in Makefile.in

---

CHANGES.188.md
hdrs/sqlite3.h

Has some important bug fixes over 3.32.1.

Update Sqlite3 to 3.32.3

---

CHANGES.188.md
Makefile.in
configure
configure.in

Also updates download link from the dead ftp.pcre.org to github.
Fixes #1355.

Update PCRE2 to 10.39

---

game/txt/hlp/penncmd.hlp
game/txt/hlp/pennfunc.hlp
game/txt/hlp/penntop.hlp

attribute functions, @atrchown, attrib-ownership

Add owner() to pertient attribute help files

---

hdrs/ansi.h
hdrs/mushtype.h
src/markup.c

This relates to Issue #1406 and the release of #1336.

Issue #1406: Fix markup

---

CHANGES.188.md
src/cque.c

- #1424: Fix crash bug in cque.c
- Update changelog

Fix for issue 1424
