pennmush/pennmush

- .travis.yml
- test/testsort.pl
This adds the necessary repository-side configuration to enable automated test runs with [Travis CI](https://travis-ci.org), a popular hosted continuous integration (CI) platform that provides free test runs for any open-source project.
Once this is merged and a webhook is added to the pennmush repo, the tests will automatically be run on every push. PRs will also be run, and the PR will get an annotation as to whether the tests passed, failed, or are pending.
For an example of what a Travis run looks like, see https://travis-ci.org/tkrajcar/pennmush/builds/55646592 - this is a run from my fork when I was testing the file.
For an example of a PR that's been tested and fails, I've set up a somewhat-silly example at https://github.com/tkrajcar/pennmush/pull/1 (note the X and check marks …
> Travis CI configuration file

- src/Makefile.in
Per conversation with @talvo, this changeset removes a compile-time dependency on `gperf`. This is relevant because currently, when you get a fresh clone and try to `make`, all of the `src/*.gperf` files are infinitesimally newer than their corresponding .c files, since the clone sets mod dates lexicographically. If you don't have `gperf` installed, your compile then fails, even though those flies are up-to-date.
> Only try to run gperf if it's present

- CHANGES.186
- game/txt/hlp/pennfunc.hlp
- game/txt/hlp/pennv186.hlp
- src/function.c
Last hardcode element of #1023.
> Add avg() -> mean() alias for Rhost compatibility.

- src/notify.c
Fixes issue #1050 
str_type() was setting the string to non ansi type if it didn't find markup, should check for ansi ESC_CHAR as well.
> str_type() wasn't checking for ansi escape codes

- .travis.yml
travis-ci updated their build infrastructure and doesn't let you use sudo anymore; just as well, as there's now a declarative syntax for providing the packages we need.
cc @talvo
> CI: Install gperf through the apt addon instead of using apt-get.

- CHANGES.186
- game/txt/hlp/pennchat.hlp
Added 'See also' references to the 'channel functions' help entry in appropriate places across the chat system help files.
> Mike347 channel functions help entries

- game/txt/hlp/penncmd.hlp
The @hook2 help entry referenced the @hook6 help entry for a list of named arguments, however, the list is actually in @hook7.
> Fix incorrect reference in the @hook2 helpentry.

- CHANGES.186
- game/txt/hlp/pennevents.hlp
- src/player.c
If using register at the login screen, pass the email to the event.
> Add email to PLAYER`CREATE event

- CHANGES.186
- src/cque.c
Enactor on a socket`connect event is -1. This confuses cque.c. So this PR fixes it.
> Fix do_second, crashing in socket`connect event

- .travis.yml
7359b25f877fe3818d1a19f95ed7642e9ed73cb7 introduced a dependency in the tests on the Perl `IO::Socket::IP` module, so that needs to be explicitly installed prior to running tests.
> CI: Install IO::Socket::IP prior to running tests.

- .travis.yml
- test/PennMUSH.pm
Includes a small tweak to the test suite to not break on Perls older than 5.18.
> CI: More perl dependency fixage

- CHANGES.186
- game/txt/hlp/pennchat.hlp
- game/txt/hlp/pennv186.hlp
- options.h.dist
- src/atr_tab.c
- src/command.c
- src/extchat.c
Adds aliases for the MUX channel system, including the commands:
```
addcom
delcom
comlist
comtitle
@clist
```
See `help muxcomsys` for details.
> Add MUX comsys aliases. You can all stop asking for it, now.

- CHANGES.186
- hdrs/extchat.h
- src/bsd.c
- src/extchat.c
This change removes dark-connect/disconnect/reconnect messages, as well as removing Dark from being used in channel messages at all.
If you connect hidden (ch from login screen), only see_all, roy or wizard players will see your hidden-connect message on ANY channel you are on.
If you are channel hidden (via @chan/hide), only see_all, roy, or wizard players will see your connect/disconnect messages on any channel you are on. (It will -not- be prefixed with HIDDEN- though).
Same rules apply for @chan/recall and crecall().  Except you can always see your own connect/disconnect messages.
This PR finalizes the disconnection (pun intended) of DARK and HIDDEN.
> Qon extchat hidden fixes

- src/sql.c
Do a proper cleanup to prevent commands from getting out of sync.
See Issue #1100
> Fix for issue #1100: MySQL Commmands out of Sync

- src/rob.c
Also, fixes a buffer over-read (noticed during testing).
I don't know whether or not people are supposed to get paid when they create a store based on the `@pricelist`/`buy` mechanic, but this is the patch to apply if they are.
> Make 'buy' pay the vendor (suggested by moniker).

- src/extchat.c
I'm a member of the Pinguem.ru competition on finding errors in open source projects. A bug, found using PVS-Studio.
Warning:
Uninitialized variable 'numblanks' used.
> Fix V614 warning from PVS-Studio Static Analyzer

- CHANGES.186
- game/txt/hlp/penncmd.hlp
- src/predicat.c
Using '=' in passwords causes problems with changing the password later using '@password', this change makes '=' an unacceptable character in passwords going forward.
Players with a '=' in the current password should be @newpassword'd by a Wizard.
As reported by Volund.
> Disallow '=' in passwords

- src/extmail.c
If `do_mail_list` is passed a `msglist` in `#<dbref>` or `*<player-name>` format, `ms.flags` is not set `M_FOLDER` by `parse_msglist`, so `AllInFolder(ms)` returns false and the player's `MAILCURF` goes unqueried. However, if (and only if) either of those types of `msglist` (or 'me') are passed to `parse_msglist`, `ms.player` is set to a nonzero value. Thus, if that nonzero value is detected here, folder should be set according to the player's `MAILCURF`.
Plus, this fixes the bug portion of issue #77.
> Make @mail pay attention to MAILCURF when passed a player or dbref.

- hdrs/conf.h
- src/bsd.c
- src/extchat.c
- src/extmail.c
- src/look.c
- src/markup.c
- src/unparse.c
This pull request adds a SUPPORT_WEBSOCKETS macro for the use_ws config option, similar to the SUPPORT_PUEBLO macro. It also adds a macro SUPPORT_HTML which is either (SUPPORT_PUEBLO || SUPPORT_WEBSOCKETS). SUPPORT_HTML is used in several places instead of SUPPORT_PUEBLO to allow HTML tags to be marked up if either Websockets or Pueblo are enabled. This enables HTML markup for Websockets, without having to turn on Pueblo for all clients.
There is also a fix to the error messages on blank input at the connect screen problem that @talvo  noticed, and that is responsible for noticing the error referenced in #1151 . This fix simply returns quietly if the command is an empty string, before proceeding with the connect command in bsd.c:check_connect().
Cheers,
-grapenut
> Allow HTML tag markup with either pueblo or websockets enabled  and fix the blank input error at connect

- CHANGES.187.md
- src/utils.c
ufun(), ulocal() would fail if you passed it an attribute name with markup / ansi. This patch removes the markup (if any) first.
> Qon fetch ufun patch

- hdrs/websock.h
- src/bsd.c
- src/websock.c
This PR includes the following 3 changes.
- Added the `send_websocket_object(DESC *d, JSON *data)` function in websock.c that can be used as an interface to send a JSON object directly to a descriptor. Can be used in a function like OOB() that bypasses the need for @pemit and wsjson() when only sending out-of-band JSON. It is necessary because @pemit will send unwanted blank newlines along with the embedded JSON.
- Updated the OOB() function to also send JSON to websocket clients. You can send the same payload to both GMCP and websocket clients allowing you to communicate with both types of clients using the same JSON API. While I think it fits perfectly to be able to send the same exact JSON payload out-of-band to either kind of client, it could also be packaged into its own …
> Out-of-band updates for websocket clients

- hdrs/pueblo.h
- src/look.c
Remove <FONT> tags from player and object names, unless explicit pueblo support is enabled. This prevents them from showing up on websockets when Pueblo is disabled, which is the default configuration.
> Remove <FONT> tags from player and object names

- hdrs/websock.h
- src/bsd.c
- src/websock.c
This is a continuation of my last PR with websocket OOB updates. Using the new cJSON utilities we add the GMCP header string to the data object. If the data is not an object we create a temporary object and add a reference to the data, using the header string as the key or "data" if it is not provided. I make sure to delete the temporary object if it was needed.
This should allow websocket clients to read and respond to any GMCP payload. Examples of the repackaged payload received by a websocket client:
```
th oob(%#,,null) -> {}
th oob(%#,,json(string,blah)) -> {"data":"blah"}
th oob(%#,header,null) -> {"gmcp":"header"}
th oob(%#,header,json(string,blah)) -> {"gmcp":"header", "header":"blah"}
th oob(%#,header,json(object,key,0)) -> {"gmcp":"header", "key":0}
```
> Update oob() to also send the GMCP headers to websockets

- CHANGES.188.md
- game/txt/hlp/pennv188.hlp
- hdrs/conf.h
- hdrs/externs.h
- hdrs/game.h
- hdrs/mushtype.h
- src/bsd.c
- src/cque.c
- src/timer.c
- src/utils.c
* Millisecond timing in bsd.c for poll() and family.
* Descriptor quota fixes and improvements
* Adjust timer.c to use milliseconds.
* Fixed msec_diff to actually return millisecond count.
* Rearranging do_second(), every_second(), etc from cque and timer since they're not run every second.
* Fixing queue_load_record to be aware it probably won't run every second.
* Cleanup of timeval, slice timeout, and related math in bsd.c
* Moved error and signal result checking in bsd.c into its own function for cleaner shovechars()
* moved gettimeofday into utils.c and made generally available as penn_gettimeofday()
* Add now_msecs(), only used by timer.c now but will be used by @wait/etc.
> Millisecond timing in bsd.c

- CHANGES.188.md
- game/mushcnf.dst
- game/txt/hlp/penncmd.hlp
- game/txt/hlp/pennconf.hlp
- game/txt/hlp/penntop.hlp
- game/txt/hlp/pennv188.hlp
- hdrs/conf.h
- hdrs/mushtype.h
- src/attrib.c
- src/bsd.c
- src/conf.c
- src/cque.c
- src/funlist.c
- src/funmisc.c
- src/game.c
- src/notify.c
- src/parse.c
- src/predicat.c
- src/set.c
- test/testatree.pl
WARNING! With the removal of the object queue, please be careful when upgrading that you do
not have any infinitely looping triggers without an `@wait`.
As an example, this used to be a common way to ensure something was executed once per second:
> `&everysecond object=do some ; updates ; @trigger me/everysecond`
This will now happen, up to several thousand times per second! Make it `@wait 1`, and it'll run once/second!
* A single command queue for players and objects. No more `@trigger` waits. [GM]
* A restructuring of bsd.c, to make it easier to reason about Penn's queue cycle. [GM]
On the way to doing this:
* cpu_timer_hit checks in atr_iter* and regexp loops (Ashen-Shugar can hang Penn for a full second w/ regrab on a single attr. Never mind max_attrs!)
* Removal of active_q_chunk - I …
> Single queue, and massive bsd.c rewrite

- CHANGES.188.md
- game/txt/hlp/pennv187.hlp
- game/txt/hlp/pennv188.hlp
- src/bsd.c
- test/PennMUSH.pm
For more details on socket quota, check GitHub issue #1221
Unit tests now run netmush with --disable-socket-quota, reducing 'make test'
run time from 6m22s to 42s
> Add --disable-socket-quota for unit tests

- CHANGES.187.md
- hdrs/mysocket.h
- src/cmds.c
- src/mysocket.c
- src/sig.c
Use it in a few places instead of current inlined setting code, and now
in @http requests. Closes #1246 
Tested on MUSH.
> Add function to set close-on-exec flag on descriptors.

- CHANGES.188.md
- config.h.in
- configure
- configure.in
- hdrs/sqlite3.h
- hdrs/sqlite3ext.h
- src/connlog.c
- src/filecopy.c
- src/help.c
- src/sql.c
Upgrade from 3.24 to 3.25. [Changes](https://sqlite.org/releaselog/3_25_0.html) include bug fixes, optimization improvements, and sql window functions.
The code for generating help entries pages has been updated to use the new window functions, which makes it much more clean and elegant (Not to mention shorter).
> Sqlite 3.25 Update

- game/txt/hlp/pennfunc.hlp
- game/txt/hlp/pennpueb.hlp
- game/txt/hlp/pennv187.hlp
This PR adds JSON functions to HELP FUNCTION LIST, and the HELP JSON FUNCTIONS entry that lists all JSON functions together. It also fixes a few minor capitalization style inconsistencies in the same files and for WebSockets.
> Add JSON to HELP FUNCTION LIST and add HELP JSON FUNCTIONS

- src/look.c
- src/unparse.c
This changes real_unparse() in unparse.c to use the ```look``` command instead of the ```examine``` command for wrapping pueblo links around object names, e.g. in your inventory or the contents of a room.
It's silly to have so many links on the screen to examine objects that you probably don't have permission to examine anyway. You can always look at anything, and that's far more likely the action you'd want to take when clicking the name from a list anyway.
This lets us remove the extra double link in look_contents() from look.c as well. Previously it was wrapped in both a look and examine command.
> Modify real_unparse() to pueblo wrap the look command instead of examine

- src/player.c
Adds a SOCKET`LOGINFAIL event for connection attempts that don't include a name/password, e.g. just typing connect. The use case for this is a login form on the web client. If your login attempt fails, it pops the login form back up and says try again. It does this just fine when you submit the incorrect username or password, but there was an early exit condition with no event queued when the name was blank. 
Uses the same event queue arguments as the "invalid player" loginfail event, with a blank string in place of the last argument for name.
> Add loginfail event for connection attempts with no name given

- src/function.c
- src/funjson.c
EDIT: **This does not enable you to embed ANSI escape sequences.** It encodes the ANSI escape character into a printable Unicode backslash-encoding. These encodings are not interpreted by the MUSH in anyway, they are just normal strings of URL-safe printable characters. The encodings are only converted back to ANSI escape if the client parses them and chooses to do that.
This PR enables ANSI encoded strings in JSON objects.  The changes are enumerated below:
1. Remove FN_STRIPANSI from the softcode declaration for json().
2. Manually strip ANSI from all args unless we're making a JSON string.
3. Render the internal markup to ANSI and immediately pass to json_escape_string() which re-encodes the escape sequences as printable characters.
With this change the code …
> Safely encode ANSI in JSON strings.

- src/bsd.c
The printf format for names in bsd.c: dump_users() was using a fixed width '%16.16s' format even though monikers with ansi may have more than 16 characters with unprintable ansi codes. Changed the format to '%s' since we are manually padding with spaces up to 16.
> Change fixed width format for names in dump_users()

- README.SSL.md
- game/mushcnf.dst
- game/txt/hlp/pennv188.hlp
- hdrs/conf.h
- hdrs/myssl.h
- hdrs/ssl_slave.h
- src/conf.c
- src/game.c
- src/myssl.c
- src/ssl_master.c
- src/ssl_slave.c
This adds a new configuration file option called ```ssl_certificate_file``` which should be set to the SSL certificate file. This allows the user to split their private key and certificates into separate files so that they can be easily symlinked back to the master certificate files (e.g. in /etc/). For backwards compatibility you can still concatenate them together and reference the combined file with ```ssl_private_key_file``` as before. For robustness (in case users are confused, etc.), you can use both ssl_certificate_file and ssl_private_key_file interchangeably, e.g. concat and put everything in ssl_certificate_file (instead of ssl_private_key_file), or put your key in ssl_certificate_file and your certificate in ssl_private_key_file. Essentially it will try to load both the key and …
> Add optional config ssl_certificate_file

- CHANGES.188.md
- config.h.in
- configure
- configure.in
- game/restart.dst
- src/bsd.c
Currently, we try to prevent multiple copies of a game from running by having the mush process create a file with its process id, and the restart script checking to see if a process with that pid is running. This has a bunch of race conditions and other issues.
This patch tries to address the worst of them by having the mush, after creating the pid file, acquire a lock on it, and exiting with a helpful failure message if it can't. That way even if two restart's are run at the same time, only one copy of the game will actually start up no matter what.
It also tweaks restart to use [flock(1)](http://man7.org/linux/man-pages/man1/flock.1.html) to check to see if a game is running, when available. (Linux, possibly other OSes), which fixes an issue where the mush isn't running but something …
> Better pidfile

- game/mushcnf.dst
- hdrs/conf.h
- src/bsd.c
- src/conf.c
This PR adds a configuration option 'index_html_file' which is commented out by default in mushcnf.dst. Setting the option to the path name of a static HTML file (game/txt/index.html by default) allows the game to use it as the default response for HTTP requests instead of the hardcoded redirect to MUDURL. If the option is blank or the file does not exist, we fall back to the original hardcoded redirect page. This uses the existing fcache_*() functions that are already used to load and serve up files like connect.txt/connect.html. This allows a game administrator to use a nicer redirect page or serve a small index.html for a web client that loads additional assets from the main website.
> Option to use a static HTML file instead of the hardcoded MUDURL redirect.

- CHANGES.188.md
- config.h.in
- configure
- configure.in
- game/mushcnf.dst
- hdrs/conf.h
- hdrs/log.h
- src/bsd.c
- src/conf.c
- src/game.c
- src/log.c
- src/memcheck.c
Logs messages through `syslog()` as well as the usual log files.
Syslog supports logging messages at different priority levels; new function `do_rawlog_lvl()` includes that level. Used in a few places as a proof of concept.
> Use syslog for logging

- CHANGES.188.md
- hdrs/version.h
- src/extmail.c
I don't have enough time to duplicate the issue in Penn to figure out if this is the actual cause and correct fix, but here's the what I'm figuring:
1) `chunk_read` doesn't null terminate. This probably doesn't impact anywhere else except mail.c since get_message might be the only one to assume it does? There's also a possibility that things are saved into chunks with null_terminator, pulled out with it, then saved again without it. Just plain ugh.
2) Replace all the `strcpy()`s in extmail.c with `mush_strncpy()`s. Also? Hate for the non-#defined numbers. 30, 50 instead of SENDER_LEN and SUBJECT_LEN, etc etc?
Thoughts on other possible causes:
1) Loading in one form of `@config chunk` and dumping in a separate might have been a cause?
2) Interplay between some particular …
> Hopefully fixes @mail going forward

- CHANGES.188.md
- src/bsd.c
Spurred by something on `<Hardcode>` a few days about about finding the version of a netmush binary.
> Add --version option.

- CHANGES.188.md
@mike347 Just fyi - the `` were triggering code formatting unintentionally, which set me off on a journey of discovery to learn how to properly use code snippets that contain backticks... turns out the answer is ... yet more backticks 😛
> Fix unescaped backticks in CHANGES.188.md.

- CHANGES.188.md
- hdrs/chunk.h
- src/boolexp.c
- src/chunk.c
- src/extmail.c
- src/markup.c
Previously, the `uint16_t` size used in `chunk.h` restricted the size of the chunk to as high as needed for increasing buffer lengths.
With the use of `uint32_t` size, it can now go up to a large enough number where `acc_chunk_init`'s ASSERT can catch it getting too high if `MAX_COMMAND_LEN` is set to `4096*4`. Before this, the game crashed before it could even reach that ASSERT.
> Issue 1336: Fix it so that mushtype.h #MAX_COMMAND_LEN can be raised.
